/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android001_ndk_HelloJNI */

#ifndef _Included_com_android001_ndk_HelloJNI
#define _Included_com_android001_ndk_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android001_ndk_HelloJNI
 * Method:    javaStaticCallJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android001_ndk_HelloJNI_javaStaticCallJniString
  (JNIEnv *, jclass);

/*
 * Class:     com_android001_ndk_HelloJNI
 * Method:    javaCallJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android001_ndk_HelloJNI_javaCallJniString
  (JNIEnv *, jobject);

/*
 * Class:     com_android001_ndk_HelloJNI
 * Method:    jniCallJavaString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android001_ndk_HelloJNI_jniCallJavaString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
