/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/*
 * Class:     com_android001_ndk_HelloJNI
 * Method:    javaStaticCallJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android001_ndk_HelloJNI_javaStaticCallJniString
        (JNIEnv * jniEnv, jclass jClz) {
    return (*jniEnv)->NewStringUTF(jniEnv,"this string from c");
}

/*
 * Class:     com_android001_ndk_HelloJNI
 * Method:    javaCallJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android001_ndk_HelloJNI_javaCallJniString
        (JNIEnv * jniEnv, jobject jobject) {

}

/*
 * Class:     com_android001_ndk_HelloJNI
 * Method:    jniCallJavaString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android001_ndk_HelloJNI_jniCallJavaString
        (JNIEnv * jniEnv, jobject jobject) {

}


